export const mockCarrier = {
  carrier_name: 'FORWARD STRONG LLC',
  carrier_address: '3234 60TH ST FL 3',
  carrier_state: 'NY',
  carrier_city: 'WOODSIDE',
  carrier_zip: '11377',
  carrier_country: 'United States',
  carrier_mc_number: '1508120',
  carrier_contact_name: null,
  carrier_phone_numbers: '+15056776787',
  carrier_fax: null,
  carrier_email: 'forwardstrongllc@gmail.com',
  carrier_website: null,
  carrier_logo: null,
  carrier_status: 0,
  billing_contact_name: null,
  billing_phone_numbers: null,
  billing_email: null,
  billing_terms: null,
  cargo_certificate: null,
  cargo_date: null,
  cargo_limit: null,
  cargo_deductible: null,
  cargo_auto_police_number: null,
  cargo_police_number: null,
  cargo_agent_name: null,
  cargo_agent_phone: null,
  cargo_status: 0,
  w9: null,
  w9_status: null,
  usdot_certificate: null,
  usdot_status: 0,
  superdispatch_client_id: 'Pe4gNOITysn8niv4iEPw1EZgdOw3qY9rxdTiRKMb',
  superdispatch_client_secret:
    '1gGZ9OXbQcazRKgeomUwA4jyI3Rxx6gWiWokslg2XR30IdHR3vzWDRBMyH3BUpRye6KXYm7xdll9OoiIFfjAFywUXqVZPOTZvcoGUGPJ24hh2EP9SgujbWjTLgAT9f2B',
  superdispatch_carrier_id: 80013,
  superdispatch_enabled: true,
  superdispatch_last_synced_at: 'Apr 12, 2026 12:01 PM',
  superdispatch_driver_default_password: '1234567'
};
